namespace MTK.Modules.Hr.Application.ApplicationsForChangeOfPosition.ExportApplicationForChangeOfPositionPdf;

public sealed record ExportApplicationForChangeOfPositionPdfResponse(Stream FileStream, string FileName);
