namespace MTK.Modules.Hr.Application.EmploymentStatusChangeApplications.ExportEmploymentStatusChangeApplicationPdf;

public sealed record ExportEmploymentStatusChangeApplicationPdfResponse(MemoryStream FileStream, string FileName);
