<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\MTK.Common.Application\MTK.Common.Application.csproj" />
    <ProjectReference Include="..\MTK.Modules.Payments.Application\MTK.Modules.Payments.Application.csproj" />
    <ProjectReference Include="..\MTK.Modules.Payments.IntegrationEvents\MTK.Modules.Payments.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Buildings\MTK.Modules.Buildings.IntegrationEvents\MTK.Modules.Buildings.IntegrationEvents.csproj" />

    <ProjectReference Include="..\..\Identity\MTK.Modules.Identity.IntegrationEvents\MTK.Modules.Identity.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Warehouse\MTK.Modules.Warehouse.IntegrationEvents\MTK.Modules.Warehouse.IntegrationEvents.csproj" />
  </ItemGroup>

</Project>
